-- MySQL Script generated by MySQL Workbench
-- Tue May 21 23:10:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema_apartado
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_apartado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_apartado` DEFAULT CHARACTER SET utf8 ;
USE `sistema_apartado` ;

-- -----------------------------------------------------
-- Table `sistema_apartado`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_apartado`.`Producto` (
  `Clave_Producto` VARCHAR(6) NULL,
  `Nombre_Producto` VARCHAR(25) NULL,
  `Tipo` VARCHAR(10) NULL,
  `Especie` VARCHAR(10) NULL,
  `Marca` VARCHAR(10) NULL,
  `Precio` FLOAT NULL,
  PRIMARY KEY (`Clave_Producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_apartado`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_apartado`.`Cliente` (
  `ID_Cliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Cliente` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_apartado`.`Apartado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_apartado`.`Apartado` (
  `Folio` VARCHAR(8) NOT NULL,
  `Concluido` TINYINT NULL,
  `Fecha` DATE NULL,
  `Fecha_Entrega` DATE NULL,
  `Total` FLOAT NULL,
  `Cantidad_Enganche` FLOAT UNSIGNED NULL,
  `Cliente_ID_Cliente` INT NOT NULL,
  `Importe` FLOAT NULL,
  PRIMARY KEY (`Folio`, `Cliente_ID_Cliente`),
  INDEX `fk_Apartado_Cliente1_idx` (`Cliente_ID_Cliente` ASC) ,
  CONSTRAINT `fk_Apartado_Cliente1`
    FOREIGN KEY (`Cliente_ID_Cliente`)
    REFERENCES `sistema_apartado`.`Cliente` (`ID_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_apartado`.`Nota_Credito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_apartado`.`Nota_Credito` (
  `ID_NotaCredito` INT NOT NULL,
  `ID_Cliente` INT NULL,
  `Folio` VARCHAR(8) NULL,
  `Cantidad_Enganche` FLOAT NULL,
  `Apartado_Folio` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`ID_NotaCredito`, `Apartado_Folio`),
  INDEX `fk_Nota_Credito_Apartado1_idx` (`Apartado_Folio` ASC) ,
  CONSTRAINT `fk_Nota_Credito_Apartado1`
    FOREIGN KEY (`Apartado_Folio`)
    REFERENCES `sistema_apartado`.`Apartado` (`Folio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_apartado`.`Nota_Liquidacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_apartado`.`Nota_Liquidacion` (
  `ID_NotaLiquidacion` INT NOT NULL,
  `Folio` VARCHAR(8) NULL,
  `Total` VARCHAR(45) NULL,
  `ID_Cliente` INT NULL,
  `Apartado_Folio` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`ID_NotaLiquidacion`, `Apartado_Folio`),
  INDEX `fk_Nota_Liquidacion_Apartado1_idx` (`Apartado_Folio` ASC) ,
  CONSTRAINT `fk_Nota_Liquidacion_Apartado1`
    FOREIGN KEY (`Apartado_Folio`)
    REFERENCES `sistema_apartado`.`Apartado` (`Folio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_apartado`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_apartado`.`Usuario` (
  `idUsuario` VARCHAR(50) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `Contrasenya` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_apartado`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_apartado`.`Venta` (
  `Apartado_Folio` VARCHAR(8) NOT NULL,
  `Producto_Clave_Producto` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`Apartado_Folio`, `Producto_Clave_Producto`),
  INDEX `fk_Apartado_has_Producto_Producto1_idx` (`Producto_Clave_Producto` ASC) ,
  INDEX `fk_Apartado_has_Producto_Apartado1_idx` (`Apartado_Folio` ASC) ,
  CONSTRAINT `fk_Apartado_has_Producto_Apartado1`
    FOREIGN KEY (`Apartado_Folio`)
    REFERENCES `sistema_apartado`.`Apartado` (`Folio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Apartado_has_Producto_Producto1`
    FOREIGN KEY (`Producto_Clave_Producto`)
    REFERENCES `sistema_apartado`.`Producto` (`Clave_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_apartado`.`Cantidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_apartado`.`Cantidades` (
  `idCantidades` INT NOT NULL AUTO_INCREMENT,
  `Subtotal` FLOAT NULL,
  `Cantidad` FLOAT NULL,
  PRIMARY KEY (`idCantidades`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_apartado`.`relacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_apartado`.`relacion` (
  `Producto_Clave_Producto` VARCHAR(6) NOT NULL,
  `Cantidades_idCantidades` INT NOT NULL,
  PRIMARY KEY (`Producto_Clave_Producto`, `Cantidades_idCantidades`),
  INDEX `fk_Producto_has_Cantidades_Cantidades1_idx` (`Cantidades_idCantidades` ASC) ,
  INDEX `fk_Producto_has_Cantidades_Producto1_idx` (`Producto_Clave_Producto` ASC) ,
  CONSTRAINT `fk_Producto_has_Cantidades_Producto1`
    FOREIGN KEY (`Producto_Clave_Producto`)
    REFERENCES `sistema_apartado`.`Producto` (`Clave_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Cantidades_Cantidades1`
    FOREIGN KEY (`Cantidades_idCantidades`)
    REFERENCES `sistema_apartado`.`Cantidades` (`idCantidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
